            - name: ServiceNow DevOps Security Results
  # You may pin to the exact commit or the version.
  # uses: ServiceNow/servicenow-devops-security-result@26f3416768ffd3991f1a14c0304ba03075724929
  uses: ServiceNow/servicenow-devops-security-result@v3.1.0
  with:
    # ServiceNow Instance URL
    instance-url: 
    # Devops Integration User Name
    devops-integration-user-name: # optional
    # Devops Integration User Password
    devops-integration-user-password: # optional
    # Devops Integration Token
    devops-integration-token: # optional
    # Github Context
    context-github: 
    # Display Name of the Job
    job-name: 
    # Security Results Attributes: For more information on defining the security attributes, View full Marketplace listing link above
    security-result-attributes: 
    # Orchestration Tool Id
    tool-id: 
          
